workflows:
  ios-minimal:
    name: iOS Minimal Build
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "DynamicGradientBorderAnimationSUI.xcodeproj"
        XCODE_SCHEME: "DynamicGradientBorderAnimationSUI"
    scripts:
      - name: Build .ipa
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

