workflows:
  ios-release:
    name: iOS Release Workflow
    environment:
      xcode: latest
      groups:
        - app_store_credentials
    scripts:
      - name: Сборка .ipa
        script: |
          xcodebuild -project DynamicGradientBorderAnimationSUI.xcodeproj \
                     -scheme DynamicGradientBorderAnimationSUI \
                     -configuration Release \
                     -archivePath $HOME/build/DynamicGradientBorderAnimationSUI.xcarchive \
                     -allowProvisioningUpdates \
                     clean archive

          xcodebuild -exportArchive \
                     -archivePath $HOME/build/DynamicGradientBorderAnimationSUI.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $HOME/build/export \
                     -allowProvisioningUpdates
    artifacts:
      - build/export/*.ipa
