workflows:
  ios-release:
    name: iOS Release Workflow
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "DynamicGradientBorderAnimationSUI.xcodeproj"
        XCODE_SCHEME: "DynamicGradientBorderAnimationSUI"
        APP_STORE_KEY_ID: "X85MC66T7S"
        APP_STORE_ISSUER_ID: "cde931e9-0b05-4235-879c-025492b1650c"
    scripts:
      - name: Сборка .ipa
        script: |
          xcodebuild -project $XCODE_PROJECT \
                     -scheme $XCODE_SCHEME \
                     -configuration Release \
                     -archivePath $HOME/build/App.xcarchive \
                     -allowProvisioningUpdates \
                     clean archive
          
          xcodebuild -exportArchive \
                     -archivePath $HOME/build/App.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $HOME/build/export \
                     -allowProvisioningUpdates
    artifacts:
      - build/export/*.ipa
    publishing:
      app_store_connect:
        submit_to_testflight: true
        authentication:
          api_key: $APP_STORE_API_KEY
          key_id: $APP_STORE_KEY_ID
          issuer_id: $APP_STORE_ISSUER_ID
