workflows:
  ios-minimal:
    name: iOS Minimal Build
    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hoki.TestRecorderScreen
      vars:
        XCODE_PROJECT: "DynamicGradientBorderAnimationSUI.xcodeproj"
        XCODE_SCHEME: "DynamicGradientBorderAnimationSUI"
    scripts:
      - name: Build .ipa
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
