workflows:
  ios-release:
    name: iOS Release Build Only
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "DynamicGradientBorderAnimationSUI.xcodeproj"
        XCODE_SCHEME: "DynamicGradientBorderAnimationSUI"
    scripts:
      - name: Build .ipa
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -archivePath $HOME/build/App.xcarchive \
                     -allowProvisioningUpdates \
                     clean archive

          xcodebuild -exportArchive \
                     -archivePath $HOME/build/App.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $HOME/build/export \
                     -allowProvisioningUpdates
    artifacts:
      - build/export/*.ipa
