workflows:
  ios-simple:
    name: Simple iOS Build
    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hoki.TestRecorderScreen
    scripts:
      - name: Codesign and build
        script: |
          keychain initialize
          app-store-connect fetch-signing-files com.hoki.TestRecorderScreen --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
          xcode-project build-ipa --project "DynamicGradientBorderAnimationSUI.xcodeproj" --scheme "DynamicGradientBorderAnimationSUI"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
